frase = 'Curso em Vídeo Python'
# print(frase[9::2])
# print(len(frase))
# print(frase.count('o', 0, 20))
# print(frase.find('eo'))
# print(frase.find('Vídeo'))
# print('Curso' in frase)
# print(frase.replace('Yarice', 'Linda'))
# print(frase.upper())
# print(frase.lower())
# print(frase.capitalize())
# print(frase.title())
# print(frase.strip())
# print(frase.rstrip())
# print(frase.lstrip())
dividido = frase.split()
print('-'.join(dividido))
print(dividido[2][3])
