frase = input('Digite uma frase: ').strip()
fraseU = frase.upper()
letraA = fraseU.count('A')
posA = (fraseU.find('A') + 1)
posU = (fraseU.rfind('A') + 1)
print(len(frase))
print(letraA)
print(posA)
print(posU)
